### ISSUE TITLE
Make helm-charts easily maintainable 

### ISSUE THREAD

**Issue by chrisseto** [redpanda-data/helm-charts#1070]
The title is just a pun on ["out of the tar pit"](https://curtclifton.net/papers/MoseleyMarks06a.pdf). I bare no ill will against helm, just writing templates for structured data.

The helm-chart is unmaintainable with the amount of resources we currently have. We're going to re-vamp the development process of the helm chart to be much more fool proof. The below task list is not yet exhaustive.

```[tasklist]
### Tasks
- [ ] #1060
- [ ] https://github.com/redpanda-data/helm-charts/issues/1077
- [ ] https://github.com/redpanda-data/helm-charts/issues/1092
- [x] Integrate `gotohelm`'s Value type parameter with json schema to allow more idiomatic gocode
- [ ] https://github.com/redpanda-data/helm-charts/issues/1081
- [ ] https://github.com/redpanda-data/helm-charts/issues/1375
- [ ] Convert the kminion chart into go code
- [ ] https://github.com/redpanda-data/helm-charts/issues/1131
```

JIRA Link: [K8S-111](https://redpandadata.atlassian.net/browse/K8S-111)

[K8S-111]: https://redpandadata.atlassian.net/browse/K8S-111?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by chrisseto** [comment]
Locking scope of this issue to the listed tasks with a target date of May 13th just to have a date that should be achievable.

**Comment by chrisseto** [comment]
I'm going to close this out as done as it's primarily an epic of epics at this point.
