### ISSUE TITLE
Revamp CI

### ISSUE THREAD

**Issue by chrisseto** [redpanda-data/helm-charts#1095]
The CI setup (in both helm-charts and the operator) are a bit all over the place right now. The recent introduce of go code into the helm-chart adds in a large chunk of untested code and now generated files that can easily get out of date. We need to comb thought the existing configurations and collapse them down into a single definition that's usable for CI and local development a like. We'll also want to rely on github actions for helping us maintain our versioning policies (#1093 ).

```[tasklist]
### Tasks
- [ ] https://github.com/redpanda-data/helm-charts/issues/1105
- [ ] https://github.com/redpanda-data/helm-charts/issues/1106
- [x] Settle on a naming convention for taskfiles
- [ ] https://github.com/redpanda-data/helm-charts/issues/1104
- [ ] https://github.com/redpanda-data/helm-charts/issues/1254
- [x] Ensure we have github actions for bumping various versions automatically and that they commit as a bot user or at least someone currently employed at redpanda.
- [ ] Utilize Github Actions for automating releases (Push a tag and have a release minted, it may be good to make some branching conventions)
- [ ] https://github.com/redpanda-data/helm-charts/issues/1097#issue-2195967108
- [ ] https://github.com/redpanda-data/helm-charts/issues/1103
- [ ] https://github.com/redpanda-data/helm-charts/issues/1109
- [ ] https://github.com/redpanda-data/helm-charts/issues/1081
```

**Comment by chrisseto** [comment]
Going to close this out and move the unfinished tickets into the backlog. We're in a pretty good place for the helm-charts and an okay place for the operator.
