### ISSUE TITLE
Vet / Verify / Test Redpanda 24.1

### ISSUE THREAD

**Issue by chrisseto** [redpanda-data/helm-charts#1098]
This work is unfortunately reactive but we need to execute a handful of tests on the beta/RC of redpanda 24.1 before it's released. We don't expect there to be any breaking changes but better safe than sorry.

As this is reactive work, it's okay to handle it as a one off. Obtaining a development build of RP and then running it through our existing test suites should be enough to cross this off the list.

Nice to haves
- [ ] An automated way of running E2E / Integration tests again a specific version of redpanda. Ideally something like `task test:e2e REDPANDA_IMAGE=...`
- [ ] A checklist for the redpanda/core team to help them better understand what type of work is likely to need support or testing from the Kubernetes team
- [ ] A nightly / weekly version of the automated tests that exercises development versions of redpanda ahead of time.

JIRA Link: [K8S-122](https://redpandadata.atlassian.net/browse/K8S-122)

[K8S-122]: https://redpandadata.atlassian.net/browse/K8S-122?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by JakeSCahill** [comment]
Write caching appears to work fine in the Topic resource with 24.1 RC 4:

```yaml
apiVersion: cluster.redpanda.com/v1alpha1
kind: Topic
metadata:
  name: test
spec:
  additionalConfig:
    write.caching: "on"
  partitions: 3
  replicationFactor: 1
  kafkaApiSpec:
    brokers:
      - "redpanda-0.redpanda.redpanda.svc.cluster.local:9093"
      - "redpanda-1.redpanda.redpanda.svc.cluster.local:9093"
      - "redpanda-2.redpanda.redpanda.svc.cluster.local:9093"
    tls:
      caCertSecretRef:
        name: "redpanda-default-cert"
        key: "ca.crt"
```

```
rpk topic describe test
SUMMARY
=======
NAME        test
PARTITIONS  3
REPLICAS    1

CONFIGS
=======
KEY                                   VALUE       SOURCE
cleanup.policy                        delete      DEFAULT_CONFIG
compression.type                      producer    DEFAULT_CONFIG
flush.bytes                           262144      DEFAULT_CONFIG
flush.ms                              100         DEFAULT_CONFIG
initial.retention.local.target.bytes  -1          DEFAULT_CONFIG
initial.retention.local.target.ms     -1          DEFAULT_CONFIG
max.message.bytes                     1048576     DEFAULT_CONFIG
message.timestamp.type                CreateTime  DEFAULT_CONFIG
redpanda.remote.delete                true        DEFAULT_CONFIG
redpanda.remote.read                  false       DEFAULT_CONFIG
redpanda.remote.write                 false       DEFAULT_CONFIG
retention.bytes                       -1          DEFAULT_CONFIG
retention.local.target.bytes          -1          DEFAULT_CONFIG
retention.local.target.ms             86400000    DEFAULT_CONFIG
retention.ms                          604800000   DEFAULT_CONFIG
segment.bytes                         134217728   DEFAULT_CONFIG
segment.ms                            1209600000  DEFAULT_CONFIG
write.caching                         on          DYNAMIC_TOPIC_CONFIG
```

**Comment by chrisseto** [comment]
@alejandroEsc @JakeSCahill I think we can close this out as done?
