### ISSUE TITLE
Convert the console chart into go code

### ISSUE THREAD

**Issue by chrisseto** [redpanda-data/helm-charts#1131]
```[tasklist]
### Tasks
- [ ] https://github.com/redpanda-data/helm-charts/issues/1392
- [ ] https://github.com/redpanda-data/helm-charts/issues/1393
- [ ] https://github.com/redpanda-data/helm-charts/issues/1394
- [ ] https://github.com/redpanda-data/helm-charts/issues/1396
- [ ] https://github.com/redpanda-data/helm-charts/issues/1395
- [ ] https://github.com/redpanda-data/helm-charts/issues/1397
- [ ] https://github.com/redpanda-data/helm-charts/issues/1398
- [ ] https://github.com/redpanda-data/helm-charts/issues/1399
- [ ] https://github.com/redpanda-data/helm-charts/issues/1400
```

JIRA Link: [K8S-134](https://redpandadata.atlassian.net/browse/K8S-134)

[K8S-134]: https://redpandadata.atlassian.net/browse/K8S-134?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
