### ISSUE TITLE
Enable OperatorV2 Usage

### ISSUE THREAD

**Issue by toddfarmer** [redpanda-data/helm-charts#1200]
```[tasklist]
### Tasks
- [ ] https://github.com/redpanda-data/helm-charts/issues/1060
- [ ] https://github.com/redpanda-data/helm-charts/issues/1092
- [ ] https://github.com/redpanda-data/helm-charts/issues/1131
- [ ] Go-ified Helm Charts are moved into the operator codebase
- [ ] https://github.com/redpanda-data/redpanda-operator/issues/91
- [ ] V1 Code and V2 Code are Consolidated
- [ ] V1 and V2 CRDs are Consolidated
```
