### ISSUE TITLE
Change rpk configuration

### ISSUE THREAD

**Issue by r-vasquez** [redpanda-data/helm-charts#658]
### What would you like to be added?

Helm Chart output includes a set of configuration flags that were changed (not deprecated, just hidden) in favor of the new `-X` flag. This was released in v23.2.

The changes are documented here: https://docs.redpanda.com/docs/get-started/intro-to-rpk/#common-configuration-properties

The goal of this issue is to change these flags in the output (for example, here: https://github.com/redpanda-data/helm-charts/blob/main/charts/redpanda/templates/_helpers.tpl#L411)

### Why is this needed?

To be consistent across our different products. A similar change is being requested in the examples of our docs: https://github.com/redpanda-data/documentation/issues/1850

Please note that these flags are not deprecated and will continue working in future releases.

Added by @joejulian:

```[tasklist]
### Tasks
- [ ] Add rpk.yaml to configmap for internal connections
- [ ] Add new configmap with rpk.yaml for external connections
- [ ] change our tests to use the new rpk.yaml
- [ ] add instructions to NOTES.txt to download the rpk.yaml and use it on the command line (make sure a test matches these instructions)
```

**Comment by joejulian** [comment]
Does this mean you _can't_ put the configs in a config file now?

**Comment by r-vasquez** [comment]
Yes, now we still support the `rpk` section in the redpanda.yaml but we encourage users to use the new profiles (rpk.yaml):

https://docs.redpanda.com/docs/get-started/config-rpk-profile/

**Comment by joejulian** [comment]
This needs to be done to fix #662. mTLS doesn't work currently.

**Comment by joejulian** [comment]
done
